import type { Metadata } from 'next'

//  Social cards, in one place, because Next does not deep-merge metadata.
//
//  A page that defines its own `openGraph` block REPLACES the root layout's
//  entirely — `images` included. So every page that set its own title silently
//  lost the site card, while still inheriting `twitter:card =
//  summary_large_image` from the root. 21 of 38 pages ended up telling crawlers
//  to render a large image card and then handing Facebook and LinkedIn nothing
//  to render, with no fallback available: those are the CSS-driven pages with
//  no <img> on them to scrape.
//
//  It stayed invisible because the two pages that DID set their own images —
//  the homepage and blog posts — are the two anyone would spot-check.
//
//  `social()` is the fix and the prevention: openGraph cannot be spelled here
//  without images, and the twitter block is DERIVED from the same object rather
//  than written alongside it, so the two cannot drift. Writing them separately
//  is what left every page advertising the homepage's title on X.

// `images` is omitted deliberately, which makes passing one a COMPILE error
// rather than a silent loss. The first version of this spread `...og` and then
// set images, so wiring blog posts through it discarded each post's own cover
// and replaced it with the site card — the same class of bug it was written to
// fix, introduced by the fix. Posts that carry a per-post image keep their own
// openGraph block; anything routed through here gets a named card.
// Distributive: Metadata['openGraph'] is a discriminated union (website,
// article, profile...), and a plain Omit over a union collapses it into one
// object type, which loses the `type` discriminant every page sets.
type OmitFrom<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never
type OpenGraph = OmitFrom<NonNullable<Metadata['openGraph']>, 'images'>

// url, alt. Cards are generated by marketing/scripts/make-og-cards.py — the
// figures on the /services card are the three published prices in
// content-engine/facts.toml, and are registered in covers.toml so the CRM
// flags them if they move. A number baked into a PNG cannot be fixed by
// editing copy.
const CARDS = {
  default: [
    '/images/og-image.png',
    'JAK Labs — operations software for local service businesses',
  ],
  about: [
    '/images/og-about.png',
    'One engineer. The person you talk to is the person building it.',
  ],
  services: [
    '/images/og-services.png',
    'Published prices — reliability audit $2,500, integration sprint from $7,500, ops build from $6,000',
  ],
  engineering: [
    '/images/og-engineering.png',
    'I am your customer — forward-deployed engineering',
  ],
  fractional: [
    '/images/og-fractional.png',
    'Part-time, in production — embedded month-to-month on your real data',
  ],
} as const

export type CardName = keyof typeof CARDS

/**
 * Returns the `openGraph` and `twitter` halves of a page's metadata, spread
 * into it. Every page on this site sets its social card through here.
 */
export function social(name: CardName, og: OpenGraph): Pick<Metadata, 'openGraph' | 'twitter'> {
  const [url, alt] = CARDS[name]
  return {
    openGraph: {
      siteName: 'JAK Labs',
      ...og,
      images: [{ url, width: 1200, height: 630, alt }],
    },
    twitter: {
      card: 'summary_large_image',
      title: og.title ?? undefined,
      description: og.description ?? undefined,
      images: [url],
    },
  }
}
