export { Hero } from './Hero'
export { Services } from './Services'
export { Industries } from './Industries'
export { WhyChooseUs } from './WhyChooseUs'
export { CTA } from './CTA'
export { ProductSpotlight } from './ProductSpotlight'
export { HoodDev } from './HoodDev'
export { Verdikt } from './Verdikt'
